# Generated by Django 4.2.7 on 2023-11-09 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('details', models.TextField(blank=True)),
                ('date', models.DateField()),
                ('status', models.CharField(choices=[('Not started', 'Not started'), ('In progress', 'In progress'), ('Completed', 'Completed')], max_length=50)),
            ],
        ),
    ]
